tag: nsga2
seed: 42

nsga:
  pop_size: 100
  num_generations: 50
  cxpb: 0.7
  mutpb: 0.2

weighted:
  pop_size: 100
  num_generations: 50
  cxpb: 0.7
  mutpb: 0.2
  weights: [0.6, 0.3, 0.1]  # [w_cost, w_reliability, w_impact]
  # Optional list of weight triplets to sweep; if provided, these override 'weights'
  # Suggested defaults include extremes and some evenly distributed combinations
  weights_list:
    - [1.0, 0.0, 0.0]  # minimize cost only
    - [0.0, 1.0, 0.0]  # maximize reliability only
    - [0.0, 0.0, 1.0]  # minimize environmental impact only
    - [0.5, 0.5, 0.0]
    - [0.5, 0.0, 0.5]
    - [0.0, 0.5, 0.5]
    - [0.33, 0.33, 0.34]
  normalization:
    cost: [0, 500000]
    reliability: [0.0, 1.0]
    impact: [0.0, 1.0]

mopso:
  swarm_size: 100
  max_iterations: 50
  archive_size: 100
  inertia_weight: 0.5
  cognitive_coeff: 1.5
  social_coeff: 1.5

bounds:
  solar_panels: [0, 500]
  wind_turbines: [0, 50]
  batteries: [0, 50]

system:
  solar:
    capacity_kw: 0.4
    cost: 300
    land_m2: 3
    lifecycle_emissions: 40
  wind:
    capacity_kw: 3.0
    cost: 6000
    land_m2: 100
    lifecycle_emissions: 800
  battery:
    capacity_kwh: 5.0
    cost: 2000
    cycle_life: 4000
    lifecycle_emissions: 150
  constraints:
    max_land_m2: 10000
    max_budget: 200000
    min_energy_kwh_per_day: 50
  project_lifetime_years: 20

data:
  source: synthetic   # synthetic | csv
  days: 365
  csv_path: ""
  aggregate_to_daily: true

output:
  base_dir: results

